services:
  db:
    ports:
      - 5454:5432
    container_name: nest-app
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=usuario
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_USER=usuario